spring:
  datasource:

    # url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-wakanda:3306/Backend_Wakanda_Salud?serverTimezone=UTC}
    # username: ${SPRING_DATASOURCE_USERNAME:root}
    # password: ${SPRING_DATASOURCE_PASSWORD:P@ssw0rd}
    url: jdbc:mysql://mysql-wakanda-1:3317/Backend-Wakanda-Agua?serverTimezone=UTC
    username: root
    password: P@ssw0rd

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

  application:
    name: backendwakandaagua

server:
  port: 8095

jwt:
  secret: securesecretkey

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    com.myproyect.springboot: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  #instance:
  # hostname: backend-wakanda-agua  # Alias DNS válido en la red
  #prefer-ip-address: true  # Usar la IP en lugar del hostname
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/} # ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true



metrics:
  export:
    prometheus:
      enabled: true